### ISSUE TITLE
descriptionの内容によってフィルタリングできるようにする

### ISSUE THREAD

**Issue by Ryota0312** [Ryota0312/mkrecord#3]
講義カレンダにはdescriptionに受講者が書かれている．
ここに自分の名前が含まれている時だけ，使いたい

**Comment by Ryota0312** [comment]
15d31bda511d9abc3c79cdda776c4f74132f3a7e

+ YAMLで以下のように設定．
+ Filter は書かなくてもおっけー．
+ summary か description どっちかだけでもおっけー．

```
Calendars:
  Univ:
    Ids:
      - "XXXXXXXXXXXX"
    Filter:
      summary: "TA"
      description "西"
```
